/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carRent.UI;

import carRent.BLL.CarBLL;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 *
 * @author noushad
 */
public class CarBookingUI extends javax.swing.JFrame {

    /**
     * Creates new form CarBookingUI
     */
    CarBLL aCarBLL;

    public CarBookingUI() {
        initComponents();
        setLocationRelativeTo(null);
        aCarBLL = new CarBLL();
        fillCombo();
    }

    private void fillCombo() {

        try {
            ListIterator litr = aCarBLL.getAllCarsRegNo().listIterator();
            while (litr.hasNext()) {
                RegNoComBoBox.addItem(litr.next().toString());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RegNoComBoBox = new javax.swing.JComboBox<>();
        customerIdTextBox = new javax.swing.JTextField();
        CustomerSearchButton = new javax.swing.JButton();
        customerNameTextBox = new javax.swing.JTextField();
        customerPhoneNoTextBox = new javax.swing.JTextField();
        TourLocation = new javax.swing.JTextField();
        toalCostTextBox = new javax.swing.JTextField();
        carBookingButton = new javax.swing.JButton();
        toDateTextBox = new javax.swing.JTextField();
        fromDateTextBox = new javax.swing.JTextField();
        customerCreationButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(464, 479));
        setName("null"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Car Registration Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 44, 140, 16);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Customer ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(86, 91, 70, 16);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Customer Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(64, 125, 92, 20);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Phone no");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(103, 163, 53, 16);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Return Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 300, 80, 16);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Total Cost");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(99, 350, 57, 16);

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Location");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(107, 201, 49, 16);

        RegNoComBoBox.setBackground(new java.awt.Color(153, 153, 153));
        RegNoComBoBox.setBorder(null);
        getContentPane().add(RegNoComBoBox);
        RegNoComBoBox.setBounds(168, 39, 160, 26);

        customerIdTextBox.setBackground(new java.awt.Color(153, 153, 153));
        customerIdTextBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(customerIdTextBox);
        customerIdTextBox.setBounds(169, 87, 70, 22);

        CustomerSearchButton.setBackground(new java.awt.Color(102, 102, 102));
        CustomerSearchButton.setForeground(new java.awt.Color(153, 153, 153));
        CustomerSearchButton.setText("Search");
        CustomerSearchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustomerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerSearchButton);
        CustomerSearchButton.setBounds(260, 90, 110, 20);

        customerNameTextBox.setEditable(false);
        customerNameTextBox.setBackground(new java.awt.Color(153, 153, 153));
        customerNameTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(customerNameTextBox);
        customerNameTextBox.setBounds(169, 123, 150, 20);

        customerPhoneNoTextBox.setEditable(false);
        customerPhoneNoTextBox.setBackground(new java.awt.Color(153, 153, 153));
        customerPhoneNoTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(customerPhoneNoTextBox);
        customerPhoneNoTextBox.setBounds(169, 159, 150, 20);

        TourLocation.setBackground(new java.awt.Color(153, 153, 153));
        TourLocation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(TourLocation);
        TourLocation.setBounds(170, 201, 150, 43);

        toalCostTextBox.setBackground(new java.awt.Color(153, 153, 153));
        toalCostTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(toalCostTextBox);
        toalCostTextBox.setBounds(174, 342, 65, 20);

        carBookingButton.setBackground(new java.awt.Color(102, 102, 102));
        carBookingButton.setForeground(new java.awt.Color(153, 153, 153));
        carBookingButton.setText("Book");
        carBookingButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBookingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carBookingButton);
        carBookingButton.setBounds(174, 378, 125, 20);

        toDateTextBox.setBackground(new java.awt.Color(153, 153, 153));
        toDateTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(toDateTextBox);
        toDateTextBox.setBounds(170, 300, 150, 20);

        fromDateTextBox.setBackground(new java.awt.Color(153, 153, 153));
        fromDateTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(fromDateTextBox);
        fromDateTextBox.setBounds(170, 260, 150, 20);

        customerCreationButton.setBackground(new java.awt.Color(102, 102, 102));
        customerCreationButton.setForeground(new java.awt.Color(153, 153, 153));
        customerCreationButton.setText("Create new ");
        customerCreationButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCreationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerCreationButton);
        customerCreationButton.setBounds(340, 140, 110, 22);

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Rent Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 260, 70, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carRent/UI/mSYE3M.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerSearchButtonActionPerformed
        // TODO add your handling code here:

        try {
            String customerIdString = customerIdTextBox.getText();
            int customerId = Integer.parseInt(customerIdString);
            ArrayList<String> customerInfo = aCarBLL.findCustomer(customerId);

            if (!customerInfo.isEmpty()) {
                customerNameTextBox.setText(customerInfo.get(0));
                customerPhoneNoTextBox.setText(customerInfo.get(1));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Customer not Present In database");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter A Valid CustomerId");
        }

    }//GEN-LAST:event_CustomerSearchButtonActionPerformed

    private void customerCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCreationButtonActionPerformed
        // TODO add your handling code here:
        new CustomerCreationUI().setVisible(true);
    }//GEN-LAST:event_customerCreationButtonActionPerformed

    private void carBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBookingButtonActionPerformed
        try {
            CustomerSearchButtonActionPerformed(evt);

            Date fromDate = null;
            Date toDate = null;

            String carRegNo = RegNoComBoBox.getSelectedItem().toString();
            String customerIdString = customerIdTextBox.getText();
            if (customerIdString.equals("")) {
                throw new Exception("Customer Id field Cannot Be Empty");
            }
            int customerId = Integer.parseInt(customerIdString);

            String customerName = customerNameTextBox.getText();

            String customerPhoneNo = customerPhoneNoTextBox.getText();

            String location = TourLocation.getText();

            if (location.equals("")) {
                throw new Exception("Location Cannot Be Empty");
            }

            String fromDateString = fromDateTextBox.getText();

            if (fromDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                fromDate = java.sql.Date.valueOf(fromDateString);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Rent Date EX:YYYY-MM-DD");
                throw new Exception("Please Enter a Valid Rent Date EX:YYYY-MM-DD");
            }

            String toDateString = toDateTextBox.getText();

            if (toDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                toDate = java.sql.Date.valueOf(toDateString);
            } catch (Exception e) {
                // JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Return Date EX:YYYY-MM-DD");
                throw new Exception("Please Enter a Valid Return Date EX:YYYY-MM-DD");
            }
            if (!toDate.after(fromDate)) {
                if (!toDate.equals(fromDate)) {
                    throw new Exception("Invalid Date Range");
                }

            }

            String totalCostString = toalCostTextBox.getText();
            if (totalCostString.equals("")) {
                throw new Exception("Total Cost Cannot Be Empty");
            }
            double totalCost = Double.parseDouble(totalCostString);

            JOptionPane.showMessageDialog(rootPane, aCarBLL.BookCar(carRegNo, customerId, customerName, customerPhoneNo, location, fromDate, toDate, totalCost));
            customerIdTextBox.setText("");
            customerNameTextBox.setText("");
            customerPhoneNoTextBox.setText("");
            TourLocation.setText("");
            fromDateTextBox.setText("");
            toDateTextBox.setText("");
            toalCostTextBox.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_carBookingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarBookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarBookingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerSearchButton;
    private javax.swing.JComboBox<String> RegNoComBoBox;
    private javax.swing.JTextField TourLocation;
    private javax.swing.JButton carBookingButton;
    private javax.swing.JButton customerCreationButton;
    private javax.swing.JTextField customerIdTextBox;
    private javax.swing.JTextField customerNameTextBox;
    private javax.swing.JTextField customerPhoneNoTextBox;
    private javax.swing.JTextField fromDateTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField toDateTextBox;
    private javax.swing.JTextField toalCostTextBox;
    // End of variables declaration//GEN-END:variables
}
