/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carRent.UI;

import carRent.BLL.CarBLL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author noushad
 */
public class CustomerCreationUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCreationUI
     */
    CarBLL aCarBLL;
    public CustomerCreationUI() {
        initComponents();
        setLocationRelativeTo(null);
        aCarBLL = new CarBLL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientNameTextBox = new javax.swing.JTextField();
        clientMobileTextBox = new javax.swing.JTextField();
        ClientSaveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Add New Customer");
        setMinimumSize(new java.awt.Dimension(437, 195));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(107, 52, 33, 16);

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Mobile Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(55, 94, 85, 16);

        clientNameTextBox.setBackground(new java.awt.Color(102, 102, 102));
        clientNameTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(clientNameTextBox);
        clientNameTextBox.setBounds(158, 48, 191, 20);

        clientMobileTextBox.setBackground(new java.awt.Color(102, 102, 102));
        clientMobileTextBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(clientMobileTextBox);
        clientMobileTextBox.setBounds(158, 90, 191, 20);

        ClientSaveButton.setBackground(new java.awt.Color(102, 102, 102));
        ClientSaveButton.setText("Save");
        ClientSaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClientSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientSaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClientSaveButton);
        ClientSaveButton.setBounds(230, 130, 120, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carRent/UI/Yellow.jpg"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(440, 480));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 430, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientSaveButtonActionPerformed
        try {
            // TODO add your handling code here:
            String name = clientNameTextBox.getText();
            String mobile = clientMobileTextBox.getText();
            JOptionPane.showMessageDialog(rootPane, aCarBLL.saveClient(name, mobile));
            clientNameTextBox.setText("");
            clientMobileTextBox.setText("");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_ClientSaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCreationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCreationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCreationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCreationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCreationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientSaveButton;
    private javax.swing.JTextField clientMobileTextBox;
    private javax.swing.JTextField clientNameTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
