/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carRent.UI;

/**
 *
 * @author noushad
 */
public class RentACarStartingUI extends javax.swing.JFrame {

    /**
     * Creates new form RentACarStartingUI
     */
    public RentACarStartingUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        carRegistrationButton = new javax.swing.JButton();
        carDetailsButton = new javax.swing.JButton();
        getIncomeDetailsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(450, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        titleLabel.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(153, 153, 153));
        titleLabel.setText("          Noushad SUper Carz Rent");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(0, 300, 380, 53);

        carRegistrationButton.setBackground(new java.awt.Color(51, 51, 51));
        carRegistrationButton.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        carRegistrationButton.setForeground(new java.awt.Color(153, 153, 153));
        carRegistrationButton.setText("Car Registration");
        carRegistrationButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegistrationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carRegistrationButton);
        carRegistrationButton.setBounds(80, 140, 290, 22);

        carDetailsButton.setBackground(new java.awt.Color(51, 51, 51));
        carDetailsButton.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        carDetailsButton.setForeground(new java.awt.Color(153, 153, 153));
        carDetailsButton.setText("Get car details");
        carDetailsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carDetailsButton);
        carDetailsButton.setBounds(80, 200, 290, 22);

        getIncomeDetailsButton.setBackground(new java.awt.Color(51, 51, 51));
        getIncomeDetailsButton.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        getIncomeDetailsButton.setForeground(new java.awt.Color(153, 153, 153));
        getIncomeDetailsButton.setText("Get income details");
        getIncomeDetailsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getIncomeDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIncomeDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getIncomeDetailsButton);
        getIncomeDetailsButton.setBounds(80, 260, 290, 22);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("REnt a car");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 80, 290, 22);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carRent/UI/6885618-luxury-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void carRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegistrationButtonActionPerformed
        // TODO add your handling code here:
        new CarRegistrationUI().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_carRegistrationButtonActionPerformed

    private void carDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carDetailsButtonActionPerformed
        // TODO add your handling code here:
        new ShowCarDetailsUI().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_carDetailsButtonActionPerformed

    private void getIncomeDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIncomeDetailsButtonActionPerformed
        // TODO add your handling code here:
        new ShowIncomeDetailsUI().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_getIncomeDetailsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CarBookingUI().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentACarStartingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentACarStartingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentACarStartingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentACarStartingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentACarStartingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carDetailsButton;
    private javax.swing.JButton carRegistrationButton;
    private javax.swing.JButton getIncomeDetailsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
