/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carRent.UI;

import carRent.BLL.CarBLL;
import carRent.DB.DAO.Car;
import carRent.DB.DAO.CarBookingDetails;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noushad
 */
public class ShowCarDetailsUI extends javax.swing.JFrame {

    /**
     * Creates new form ShowCarDetailsUI
     */
    private CarBLL aCarBLL;

    public ShowCarDetailsUI() {
        initComponents();
        setLocationRelativeTo(null);
        aCarBLL = new CarBLL();
        fillCombo();
        getDefinedCars(null, null, null);

    }

    private void fillCombo() {

        try {
            ListIterator litr = aCarBLL.getAllCarsRegNo().listIterator();
            while (litr.hasNext()) {
                CarRegNoComboBox.addItem(litr.next().toString());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CarDetailsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CarRegNoComboBox = new javax.swing.JComboBox<>();
        QueryButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromDateTextBox = new javax.swing.JTextField();
        toDateTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Get Details Of A Car");
        setMinimumSize(new java.awt.Dimension(690, 700));
        setPreferredSize(new java.awt.Dimension(685, 685));
        setResizable(false);
        getContentPane().setLayout(null);

        CarDetailsTable.setBackground(new java.awt.Color(102, 102, 102));
        CarDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rented By", "Car Reg No", "From", "Till", "Location", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CarDetailsTable);
        if (CarDetailsTable.getColumnModel().getColumnCount() > 0) {
            CarDetailsTable.getColumnModel().getColumn(0).setResizable(false);
            CarDetailsTable.getColumnModel().getColumn(1).setResizable(false);
            CarDetailsTable.getColumnModel().getColumn(2).setResizable(false);
            CarDetailsTable.getColumnModel().getColumn(3).setResizable(false);
            CarDetailsTable.getColumnModel().getColumn(4).setResizable(false);
            CarDetailsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 210, 620, 440);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Car Reg No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 34, 63, 16);

        CarRegNoComboBox.setBackground(new java.awt.Color(102, 102, 102));
        CarRegNoComboBox.setForeground(new java.awt.Color(204, 204, 204));
        CarRegNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRegNoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CarRegNoComboBox);
        CarRegNoComboBox.setBounds(108, 29, 131, 26);

        QueryButton.setBackground(new java.awt.Color(102, 102, 102));
        QueryButton.setForeground(new java.awt.Color(204, 204, 204));
        QueryButton.setText("Query");
        QueryButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(QueryButton);
        QueryButton.setBounds(150, 140, 90, 22);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("From Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(19, 73, 58, 16);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("To Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(34, 111, 43, 16);

        fromDateTextBox.setBackground(new java.awt.Color(102, 102, 102));
        fromDateTextBox.setForeground(new java.awt.Color(204, 204, 204));
        fromDateTextBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(fromDateTextBox);
        fromDateTextBox.setBounds(108, 65, 131, 22);

        toDateTextBox.setBackground(new java.awt.Color(102, 102, 102));
        toDateTextBox.setForeground(new java.awt.Color(204, 204, 204));
        toDateTextBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(toDateTextBox);
        toDateTextBox.setBounds(108, 107, 131, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carRent/UI/Wooden-Solid-Dark-Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarRegNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRegNoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarRegNoComboBoxActionPerformed

    private void QueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryButtonActionPerformed
        // TODO add your handling code here:
        try {
            Date fromDate = null;
            Date toDate = null;

            String carRegNo = CarRegNoComboBox.getSelectedItem().toString();
           
            String fromDateString = fromDateTextBox.getText();

            if (fromDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                fromDate = java.sql.Date.valueOf(fromDateString);
            } catch (Exception e) {
               //JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Date EX:YYYY-MM-DD");
               throw new Exception("Please Enter a Valid Date EX:YYYY-MM-DD");
            }

            String toDateString = toDateTextBox.getText();
            if (toDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                toDate = java.sql.Date.valueOf(toDateString);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Date EX:YYYY-MM-DD");
                 throw new Exception("Please Enter a Valid Date EX:YYYY-MM-DD");
            }

            if (!toDate.after(fromDate)) {
                if (!toDate.equals(fromDate)) {
                    throw new Exception("Invalid Date Range");
                }

            }
            try {
                getDefinedCars(carRegNo, fromDate, toDate);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(rootPane, "Please Fill All required Fields With Valid Entries");
                 throw new Exception("Please Fill All required Fields With Valid Entries");
            }
            fromDateTextBox.setText("");
            toDateTextBox.setText("");
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_QueryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCarDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCarDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCarDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCarDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCarDetailsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarDetailsTable;
    private javax.swing.JComboBox<String> CarRegNoComboBox;
    private javax.swing.JButton QueryButton;
    private javax.swing.JTextField fromDateTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField toDateTextBox;
    // End of variables declaration//GEN-END:variables

    private void getDefinedCars(String carRegNo, Date fromDate, Date toDate) {
        try {
            String[] columnNames = {"CUSTOMER NAME", "CAR REG NO", "RENT DATE", "RETURN DATE", "LOCATION", "PRICE"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            CarDetailsTable.setModel(model);
            ListIterator litr = aCarBLL.getDefinedCars(carRegNo, fromDate, toDate).listIterator();
            while (litr.hasNext()) {
                CarBookingDetails aBookingDetail = (CarBookingDetails) litr.next();
                model.addRow(new Object[]{aBookingDetail.getCustomerName(), aBookingDetail.getCarRegNo(), aBookingDetail.getRentDate().toString(), aBookingDetail.getReturnDate().toString(), aBookingDetail.getLocation(), aBookingDetail.getPrice().toString()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
}
