/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carRent.UI;

import carRent.BLL.CarBLL;
import carRent.DB.DAO.CarBookingDetails;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noushad
 */
public class ShowIncomeDetailsUI extends javax.swing.JFrame {

    /**
     * Creates new form ShowIncomeDetailsUI
     */
    CarBLL aCarBLL;

    public ShowIncomeDetailsUI() {
        initComponents();
        setLocationRelativeTo(null);
        aCarBLL = new CarBLL();
        getDefinedInfo(null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromDateTextBox = new javax.swing.JTextField();
        toDateTextBox = new javax.swing.JTextField();
        GoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarDetailsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalEarningTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Cash Box");
        setMinimumSize(new java.awt.Dimension(675, 540));
        setPreferredSize(new java.awt.Dimension(675, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("From");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(62, 43, 29, 16);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("To");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(77, 85, 14, 16);

        fromDateTextBox.setBackground(new java.awt.Color(204, 204, 204));
        fromDateTextBox.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(fromDateTextBox);
        fromDateTextBox.setBounds(109, 39, 140, 24);

        toDateTextBox.setBackground(new java.awt.Color(204, 204, 204));
        toDateTextBox.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(toDateTextBox);
        toDateTextBox.setBounds(109, 81, 140, 24);

        GoButton.setBackground(new java.awt.Color(153, 153, 153));
        GoButton.setForeground(new java.awt.Color(204, 204, 204));
        GoButton.setText("GO");
        GoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoButton);
        GoButton.setBounds(142, 123, 110, 20);

        CarDetailsTable.setForeground(new java.awt.Color(102, 102, 102));
        CarDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rented By", "Car Reg No", "From", "Till", "Location", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CarDetailsTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 630, 275);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Total Earnings : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(166, 476, 90, 16);

        totalEarningTextBox.setEditable(false);
        totalEarningTextBox.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(totalEarningTextBox);
        totalEarningTextBox.setBounds(274, 468, 150, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carRent/UI/black-wood-texture-wallpaper-wallpaper-1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 670, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        // TODO add your handling code here:
        try {
            Date fromDate = null;
            Date toDate = null;
            String fromDateString = fromDateTextBox.getText();

            if (fromDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                fromDate = java.sql.Date.valueOf(fromDateString);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Date EX:YYYY-MM-DD");
                throw new Exception("Please Enter a Valid Date EX:YYYY-MM-DD");
            }
            String toDateString = toDateTextBox.getText();
            if (toDateString.equals("")) {
                throw new Exception("Date Field Cannot Be Empty");
            }
            try {
                toDate = java.sql.Date.valueOf(toDateString);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Date EX:YYYY-MM-DD");
                throw new Exception("Please Enter a Valid Date EX:YYYY-MM-DD");
            }

            if (!toDate.after(fromDate)) {
                if (!toDate.equals(fromDate)) {
                    throw new Exception("Invalid Date Range");
                }

            }
            try {
                getDefinedInfo(fromDate, toDate);
            } catch (Exception e) {
                throw new Exception("Please Fill All required Fields With Valid Entries");
            }
            getTotalIncome(fromDate,toDate);
            fromDateTextBox.setText("");
            toDateTextBox.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_GoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowIncomeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowIncomeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowIncomeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowIncomeDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowIncomeDetailsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarDetailsTable;
    private javax.swing.JButton GoButton;
    private javax.swing.JTextField fromDateTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField toDateTextBox;
    private javax.swing.JTextField totalEarningTextBox;
    // End of variables declaration//GEN-END:variables

    private void getDefinedInfo(Date fromDate, Date toDate) {
        try {
            String[] columnNames = {"CUSTOMER NAME", "CAR REG NO", "RENT DATE", "RETURN DATE", "LOCATION", "PRICE"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            CarDetailsTable.setModel(model);
            ListIterator litr = aCarBLL.getDefinedInfo(fromDate, toDate).listIterator();
            while (litr.hasNext()) {
                CarBookingDetails aBookingDetail = (CarBookingDetails) litr.next();
                model.addRow(new Object[]{aBookingDetail.getCustomerName(), aBookingDetail.getCarRegNo(), aBookingDetail.getRentDate().toString(), aBookingDetail.getReturnDate().toString(), aBookingDetail.getLocation(), aBookingDetail.getPrice().toString()});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void getTotalIncome(Date fromDate,Date toDate) {
        try {
            Double totalIncome = aCarBLL.getTotalIncome(fromDate,toDate);
            String totalIncomeString = totalIncome.toString();
            totalEarningTextBox.setText(totalIncomeString);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }
}
